# Generated by Django 4.1.4 on 2022-12-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(choices=[('CALZA DE DIENTE', 'CALZA DE DIENTE'), ('BRACKETS', 'BRACKETS')], default='CALZA DE DIENTE', max_length=100, verbose_name='Tipo de tratamiento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patients', verbose_name='Paciente')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatment.treatment', verbose_name='Tratamiento')),
            ],
            options={
                'verbose_name': 'Tratamiento Paciente',
                'verbose_name_plural': 'Tratamientos Pacientes',
            },
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ManyToManyField(through='treatment.TreatmentPatient', to='patient.patients'),
        ),
    ]
