# Generated by Django 4.1.4 on 2022-12-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('treatment', '0002_alter_treatment_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ManyToManyField(blank=True, null=True, through='treatment.TreatmentPatient', to='patient.patients'),
        ),
    ]
