# Generated by Django 4.1.4 on 2022-12-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('treatment', '0004_alter_treatmentpatient_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentpatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patients', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='treatmentpatient',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatment.treatment', verbose_name='Tratamiento'),
        ),
    ]
