# Generated by Django 4.1.4 on 2022-12-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patients_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='image',
        ),
    ]
